### ISSUE TITLE
USER STORY: Manage user profile

### ISSUE THREAD

**Issue by CeciliaSG** [CeciliaSG/members-only#20]
As a logged in user I can access my profile so that I can manage the profile.

# Acceptance Criteria

- Acceptance criteria 1: Users can view their profile information.

- Acceptance criteria 2: Users can update their profile information.

- Acceptance criteria 3: Users can delete their profile and all information associated with it.

# Tasks

- [ ] Task 1: Create profile page which renders the profile information/form.
- [ ] Task 2: Create functionality so that the profile information can be updated.
- [ ] Task 3: Create functionality so that the profile information can be deleted.

**Comment by CeciliaSG** [comment]
This is done.
