### ISSUE TITLE
USER STORY: Create and manage events

### ISSUE THREAD

**Issue by CeciliaSG** [CeciliaSG/members-only#21]
As a staff I can create events in the admin so that users can see them and rsvp.

USER STORY:

As a logged in user I want to be able to access the events page and RSVP to events.

# Acceptance Criteria

- Acceptance criteria 1: As an admin/staff I want to be able to create events and display them on the events page.

- Acceptance criteria 2: As an admin I want to be able to view/administer rsvps in the admin.

- Acceptance criteria 3: As an admin I want to be able to respond to users who have rsvp:ed to events.

# Tasks
- [x] Task 1: Create event list and event details page.
- [x] Task 2: Create rsvp functionality.
- [ ] Task 3: Create functionality to respond to users from the admin.
