### ISSUE TITLE
USER STORY: View and RSVP to events

### ISSUE THREAD

**Issue by CeciliaSG** [CeciliaSG/members-only#22]
As a user I can view a list of events and details of the event so that I can RSVP.

# Acceptance Criteria

- Acceptance criteria 1: Logged in users can view an events list.
- Acceptance criteria 2: Logged in users can view a details_page for an individual event.
- Acceptance criteria 3: Logged in users can RSVP to events.

# Tasks

- [x] Task 1: Create event list and event details page.
- [x] Task 2: Create rsvp functionality.
- [x] Task 3: Include email functionality to send conf. email when rsvp is sent.
