### ISSUE TITLE
USER STORY: When the page isn't available

### ISSUE THREAD

**Issue by CeciliaSG** [CeciliaSG/members-only#34]
As a user I see a 404 page so that I know the page I am trying to access isn't available.

# Acceptance Criteria

- Acceptance criteria 1: 404 is displayed when a user tries to access a page that isn't available.

- Acceptance criteria 2

- Acceptance criteria 3

# Tasks

- [x] Task 1: create 404 view
- [x] Task 2: crete 404 url
- [x] Task 3: create 404 template

**Comment by CeciliaSG** [comment]
Done
