### ISSUE TITLE
USER STORY: Delete user account/profile and all related info.

### ISSUE THREAD

**Issue by CeciliaSG** [CeciliaSG/members-only#43]
As a **user** I can **delete my account** so that **I know that my information isn't available to the company when I am no longer a member**

# Acceptance Criteria

- Acceptance criteria 1: Account is deleted.
- Acceptance criteria 2: All related user information is deleted.
- Acceptance criteria 2: Link is clearly visible in the dropdown meny visible to logged-in users.

# Tasks

- [x] Task 1: Create delete account function.
- [x] Task 2: Create delete account template.
- [x] Task 3: Add link to dropdown menu.

**Comment by CeciliaSG** [comment]
Done
