### ISSUE TITLE
USER STORY: Map

### ISSUE THREAD

**Issue by CeciliaSG** [CeciliaSG/members-only#45]
As a **user** I can **find pins for the restaurants, bars, events etc. on a map** so that **I can easily locate them in the city.**

# Acceptance Criteria

- Acceptance criteria 1: Map accessible in the top navbar.

- Acceptance criteria 2: All restos, bars, events etc. are pinned on the map.

# Tasks

- [ ] Task 1: Create and add map function.
- [ ] Task 2: Make it accessible from top navbar.
- [ ] Task 3: Pinn all restos, bars etc. on map.
